export type ArticleBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; text: string }
  | { type: "list"; items: string[] };

export type Article = {
  slug: string;
  title: string;
  category: string;
  date: string;
  updatedDate: string;
  author: string;
  readingTime: string;
  featuredImage: string;
  excerpt: string;
  demoContent: boolean;
  consentStatus: string;
  relatedProject: string | null;
  relatedLocation: string | null;
  body: ArticleBlock[];
};

export const articles: Article[] = [
  {
    slug: "why-solar-lighting-changes-more-than-a-home",
    title: "Why Solar Lighting Changes More Than a Home",
    category: "Project Updates",
    date: "Field note",
    updatedDate: "Field note",
    author: "The Daily Bread Project",
    readingTime: "4 min read",
    featuredImage: "/images/programs/solar-lighting-realistic.png",
    excerpt: "Solar lighting can affect safety, study time, family routines, and the everyday dignity of a household.",
    demoContent: false,
    consentStatus: "No individual story featured",
    relatedProject: "solar-100-homes",
    relatedLocation: null,
    body: [
      { type: "paragraph", text: "When people think about solar lighting, they usually think about one simple thing: turning on a light." },
      { type: "paragraph", text: "But for a family living without dependable electricity, light changes much more than the room they are standing in. It can change how safe they feel, how children learn, how a household functions, and how people move through their everyday lives." },
      { type: "paragraph", text: "Something as basic as lighting can become the difference between ending the day when the sun goes down and having a few more productive hours to study, prepare meals, work, pray, plan, or simply spend time together." },
      { type: "paragraph", text: "That is why solar lighting is such an important part of the work we want to do through The Daily Bread Project." },
      { type: "heading", text: "Light creates a safer home" },
      { type: "paragraph", text: "When a home is dark at night, everyday movement becomes harder." },
      { type: "paragraph", text: "Walking from one room to another can become risky. Cooking becomes more difficult. Caring for children, older relatives, or anyone with mobility challenges becomes more stressful. Families may also rely on candles, kerosene lamps, or other temporary lighting sources that can create fire hazards, smoke, and additional household expenses." },
      { type: "paragraph", text: "Solar lighting offers a safer alternative." },
      { type: "paragraph", text: "A reliable light near an entrance, cooking area, sleeping space, or outdoor walkway can help reduce avoidable accidents and make families feel more secure in their own homes." },
      { type: "paragraph", text: "It does not solve every challenge, but it removes one burden from the household. And sometimes removing one daily burden creates room for a family to breathe." },
      { type: "heading", text: "Light gives children more time to learn" },
      { type: "paragraph", text: "Many children return home from school with homework, reading assignments, or lessons they still need to review." },
      { type: "paragraph", text: "Without dependable lighting, that work may stop when daylight disappears. Some children may attempt to study by candlelight, phone flashlights, or dim lamps. Others may not be able to study at all." },
      { type: "paragraph", text: "Solar lighting gives children a safer, more consistent space to read and complete schoolwork after dark." },
      { type: "paragraph", text: "That extra study time matters. It can help a child feel more prepared in class, build confidence, and stay connected to their education. It also gives parents and caregivers a better opportunity to support them." },
      { type: "paragraph", text: "A solar light may look like a small item, but to a student, it can represent more time, more focus, and more opportunity." },
      { type: "heading", text: "Light supports the rhythm of family life" },
      { type: "paragraph", text: "Every household has a routine." },
      { type: "paragraph", text: "Meals must be prepared. Children must be cared for. Clothes may need to be sorted. Household supplies must be organized. Families need time to talk, plan, and prepare for the next day." },
      { type: "paragraph", text: "When lighting is limited, all of those responsibilities have to be completed quickly or postponed." },
      { type: "paragraph", text: "Reliable solar lighting allows a household to continue functioning after sunset." },
      { type: "paragraph", text: "A mother can finish preparing food. A widow can organize her home without rushing. A family can gather together. A small business owner may be able to prepare products, review inventory, or complete simple tasks in the evening." },
      { type: "paragraph", text: "Light creates time, and time can create stability." },
      { type: "heading", text: "Light can reduce household expenses" },
      { type: "paragraph", text: "Families without dependable electricity often spend money repeatedly on temporary lighting options." },
      { type: "paragraph", text: "Candles, batteries, fuel, and phone charging fees can slowly take money away from food, transportation, school needs, and other essentials." },
      { type: "paragraph", text: "Solar lighting can help reduce those recurring costs." },
      { type: "paragraph", text: "While the initial equipment must be funded and properly installed, the long-term benefit may be meaningful for households already working with limited resources." },
      { type: "paragraph", text: "The goal is not simply to provide a product. The goal is to provide something practical that continues helping after the first day. That is the kind of support we believe in." },
      { type: "heading", text: "Light restores dignity" },
      { type: "paragraph", text: "Dignity is not only about surviving. It is about being able to live, care for your family, and move through your home with a sense of security and normalcy." },
      { type: "paragraph", text: "No one should have to feel forgotten because their community lacks reliable infrastructure. No parent should have to choose between buying food and purchasing fuel just to keep a light on for a few hours." },
      { type: "paragraph", text: "Solar lighting can help a family feel seen." },
      { type: "paragraph", text: "It says, \"Your safety matters. Your children's education matters. Your household matters.\" That message is just as important as the equipment itself." },
      { type: "heading", text: "Our approach" },
      { type: "paragraph", text: "Through The Daily Bread Project, our goal is to support solar-lighting initiatives in partnership with trusted local leaders and communities." },
      { type: "paragraph", text: "We do not want to walk into a community assuming we already know what people need. We want to listen, understand the local conditions, identify the right households, review practical costs, and support solutions that make sense for the people receiving them." },
      { type: "paragraph", text: "Every project should be approached with transparency, care, and respect." },
      { type: "paragraph", text: "That means confirming the need, understanding installation and maintenance requirements, documenting how funds are used, and sharing honest updates with supporters." },
      { type: "paragraph", text: "We are not interested in creating impressive numbers for a website. We are interested in creating practical change that families can actually feel." },
      { type: "heading", text: "More than a light" },
      { type: "paragraph", text: "A solar light may not look like a major development project. But inside a home, it can mean:" },
      { type: "list", items: ["A safer evening routine", "More time for a child to study", "Fewer household lighting expenses", "Reduced use of candles or unsafe fuel sources", "More time to prepare for the next day", "A stronger sense of security and dignity"] },
      { type: "paragraph", text: "That is why solar lighting changes more than a home. It changes what is possible inside that home." },
      { type: "paragraph", text: "And when practical help reaches one household at a time, it can slowly strengthen an entire community." },
    ],
  },
  {
    slug: "supporting-widows-with-dignity",
    title: "Supporting Widows With Dignity",
    category: "Stories of Impact",
    date: "Field note",
    updatedDate: "Field note",
    author: "The Daily Bread Project",
    readingTime: "3 min read",
    featuredImage: "/images/updates/widow-support-dignity.png",
    excerpt: "Dignity-centered support avoids pity and focuses on practical help, privacy, and respect.",
    demoContent: false,
    consentStatus: "No individual story featured",
    relatedProject: null,
    relatedLocation: null,
    body: [
      { type: "paragraph", text: "Supporting a widow should never feel like putting her pain on display." },
      { type: "paragraph", text: "It should not require her to repeatedly explain her hardest moments, prove that she is suffering enough, or stand in front of a camera just to receive help." },
      { type: "paragraph", text: "Real support begins with dignity." },
      { type: "paragraph", text: "At The Daily Bread Project, we believe widows deserve to be treated as whole people, not as sad stories, charity cases, or fundraising images." },
      { type: "paragraph", text: "They are mothers, leaders, caregivers, workers, business owners, aunties, neighbors, mentors, and women with dreams, wisdom, and strength." },
      { type: "paragraph", text: "They may be walking through a difficult season, but that season does not define their entire identity." },
      { type: "heading", text: "Help should feel respectful" },
      { type: "paragraph", text: "Asking for help can be uncomfortable." },
      { type: "paragraph", text: "Many women are used to holding everything together for their families. They may already feel pressure to stay strong, hide their needs, and avoid becoming a burden to others." },
      { type: "paragraph", text: "When support is offered carelessly, it can add embarrassment to an already painful situation." },
      { type: "paragraph", text: "That is why the way help is given matters." },
      { type: "paragraph", text: "Respectful support means:" },
      { type: "list", items: ["Speaking with kindness", "Protecting personal information", "Avoiding unnecessary questions", "Not sharing photos without permission", "Allowing women to receive help privately", "Listening before making assumptions", "Offering practical choices whenever possible"] },
      { type: "paragraph", text: "Dignity-centered support asks, \"How can we help in a way that honors you?\"" },
      { type: "heading", text: "Practical support matters" },
      { type: "paragraph", text: "Prayer, encouragement, and emotional support are meaningful, but practical needs still have to be met." },
      { type: "paragraph", text: "A widow may need help with:" },
      { type: "list", items: ["Food", "Household supplies", "School expenses", "Transportation", "Hygiene products", "Temporary emergency assistance", "Budgeting guidance", "Referrals to local resources", "Skills or income opportunities"] },
      { type: "paragraph", text: "The need may look different from one household to another." },
      { type: "paragraph", text: "One woman may need immediate groceries. Another may need help organizing household expenses after losing her spouse's income. Someone else may need a connection to training, work, or a trusted community resource." },
      { type: "paragraph", text: "There is no one-size-fits-all response. That is why listening is essential." },
      { type: "heading", text: "Privacy is part of compassion" },
      { type: "paragraph", text: "A person should not have to give up her privacy to receive help." },
      { type: "paragraph", text: "Stories can inspire people to give, but the person behind the story must always come first." },
      { type: "paragraph", text: "Before sharing a widow's name, photo, location, or personal experience, organizations should receive clear permission and explain how the information will be used." },
      { type: "paragraph", text: "When consent is not appropriate or available, details should remain private." },
      { type: "paragraph", text: "Compassion does not expose people. Compassion protects them." },
      { type: "heading", text: "Support should not create dependency" },
      { type: "paragraph", text: "Emergency help is important, but long-term support should also create pathways toward stability." },
      { type: "paragraph", text: "That may include:" },
      { type: "list", items: ["Financial education", "Budgeting support", "Skills development", "Business guidance", "Employment referrals", "Community partnerships", "Mentorship", "Access to practical resources"] },
      { type: "paragraph", text: "The goal is not to make someone feel permanently dependent on an organization. The goal is to help her regain stability, confidence, and options." },
      { type: "heading", text: "Seeing the woman, not just the need" },
      { type: "paragraph", text: "It is easy to focus on what a person lacks." },
      { type: "paragraph", text: "Dignity-centered support also recognizes what she carries." },
      { type: "paragraph", text: "She may have experience, knowledge, faith, talents, relationships, and ideas that can help rebuild her future." },
      { type: "paragraph", text: "Supporting widows should include room for their voices." },
      { type: "paragraph", text: "Ask what they need. Ask what they want to work toward. Ask what would make the greatest difference in their household." },
      { type: "paragraph", text: "Sometimes the most respectful thing we can do is stop assuming and start listening." },
      { type: "heading", text: "Our commitment" },
      { type: "paragraph", text: "The Daily Bread Project is committed to helping widows in a way that protects privacy, preserves dignity, and provides practical support." },
      { type: "paragraph", text: "We will not use pain as entertainment. We will not turn someone's hardship into a marketing tool. We will not make promises we cannot keep." },
      { type: "paragraph", text: "We want every woman we serve to feel respected, heard, and valued." },
      { type: "paragraph", text: "Because the goal is not simply to help someone get through today. The goal is to remind her that her life still carries purpose, her voice still matters, and her future is still worth building." },
    ],
  },
  {
    slug: "from-immediate-relief-to-long-term-stability",
    title: "From Immediate Relief to Long-Term Stability",
    category: "Financial Education",
    date: "Field note",
    updatedDate: "Field note",
    author: "The Daily Bread Project",
    readingTime: "5 min read",
    featuredImage: "/images/updates/family-stability-planning.png",
    excerpt: "Relief matters most when it opens a pathway toward steady household planning and long-term strength.",
    demoContent: false,
    consentStatus: "No individual story featured",
    relatedProject: "family-stability",
    relatedLocation: null,
    body: [
      { type: "paragraph", text: "Immediate relief matters." },
      { type: "paragraph", text: "When a family does not have enough food, the first priority is not a five-year financial plan. It is making sure they can eat." },
      { type: "paragraph", text: "When a widow is facing an urgent household need, the first conversation should not begin with a lecture about budgeting. It should begin with compassion, listening, and practical help." },
      { type: "paragraph", text: "Relief meets the need in front of us. But if support ends there, the same family may return to the same crisis again and again." },
      { type: "paragraph", text: "That is why The Daily Bread Project believes relief should become a doorway to stability." },
      { type: "heading", text: "Relief helps people breathe" },
      { type: "paragraph", text: "Financial stress affects more than a bank account." },
      { type: "paragraph", text: "It can affect sleep, decision-making, relationships, health, confidence, and the ability to think clearly." },
      { type: "paragraph", text: "When someone is worried about food, transportation, electricity, school supplies, or basic household needs, it becomes difficult to plan beyond the next few days." },
      { type: "paragraph", text: "Immediate relief can create breathing room." },
      { type: "paragraph", text: "A food package, emergency resource, household supply, or temporary expense payment may reduce enough pressure for a family to pause and think about what comes next." },
      { type: "paragraph", text: "That pause matters. People make stronger decisions when they are not operating in constant panic." },
      { type: "heading", text: "Stability starts with understanding the household" },
      { type: "paragraph", text: "Every family's financial situation is different." },
      { type: "paragraph", text: "Some households have inconsistent income. Others may have stable income but high debt. Some are managing medical expenses, school costs, caregiving responsibilities, or transportation challenges." },
      { type: "paragraph", text: "Before recommending solutions, we must understand the household." },
      { type: "paragraph", text: "Helpful questions may include:" },
      { type: "list", items: ["What income is currently coming into the home?", "Which expenses must be paid every month?", "Which bills are overdue?", "Are there debts or emergency expenses?", "What resources are already available?", "What skills or income opportunities exist?", "What is the family's most urgent goal?"] },
      { type: "paragraph", text: "This is not about judging how someone spends money. It is about creating a clear picture." },
      { type: "paragraph", text: "You cannot build a realistic plan around numbers you do not understand." },
      { type: "heading", text: "A simple budget can bring clarity" },
      { type: "paragraph", text: "The word \"budget\" can feel restrictive, especially when money is already tight." },
      { type: "paragraph", text: "But a budget is not punishment. It is simply a plan for the money available." },
      { type: "paragraph", text: "A simple household budget should answer four questions:" },
      { type: "list", items: ["How much money is coming in?", "What must be paid first?", "What can be adjusted?", "What needs immediate attention?"] },
      { type: "paragraph", text: "The goal is not perfection. The goal is awareness." },
      { type: "paragraph", text: "A family may discover that the problem is not overspending but insufficient income. Another household may find several small expenses that can be reduced. Someone else may realize bills need to be reorganized around payment dates." },
      { type: "paragraph", text: "The budget helps identify the real issue." },
      { type: "heading", text: "Stability requires priorities" },
      { type: "paragraph", text: "When money is limited, every expense cannot be treated equally." },
      { type: "paragraph", text: "Households may need to prioritize:" },
      { type: "list", items: ["Food", "Housing", "Utilities", "Medication", "Transportation", "School needs", "Essential household items", "Minimum debt obligations"] },
      { type: "paragraph", text: "After those needs are reviewed, the family can look at what can be delayed, reduced, renegotiated, or eliminated." },
      { type: "paragraph", text: "This process should be practical and shame-free. People do not need to be embarrassed into making better decisions. They need clear information, realistic options, and support." },
      { type: "heading", text: "Emergency savings can begin small" },
      { type: "paragraph", text: "Many people hear \"emergency fund\" and assume they need to save thousands of dollars immediately." },
      { type: "paragraph", text: "That can feel impossible." },
      { type: "paragraph", text: "A better starting point may be:" },
      { type: "list", items: ["Saving the first $25", "Then reaching $100", "Then working toward one week of essential expenses", "Eventually building a larger cushion"] },
      { type: "paragraph", text: "Small savings still matter. Even a modest amount can help cover transportation, medication, food, or a small household emergency without immediately borrowing money." },
      { type: "paragraph", text: "The habit is just as important as the amount. Consistency builds confidence." },
      { type: "heading", text: "Income matters too" },
      { type: "paragraph", text: "Budgeting alone cannot solve every financial problem." },
      { type: "paragraph", text: "Sometimes there is simply not enough money coming into the household." },
      { type: "paragraph", text: "Long-term stability may require income support through:" },
      { type: "list", items: ["Job referrals", "Skills training", "Small business education", "Employment preparation", "Community connections", "Trade opportunities", "Mentorship", "Financial coaching"] },
      { type: "paragraph", text: "A family should not be made to feel like they failed because expenses exceed income. Sometimes the next step is not cutting more. Sometimes the next step is creating more opportunity." },
      { type: "heading", text: "Financial education should feel practical" },
      { type: "paragraph", text: "Financial education is most helpful when people can apply it immediately." },
      { type: "paragraph", text: "It should not be filled with complicated language, unrealistic examples, or advice designed for households with completely different resources." },
      { type: "paragraph", text: "Helpful financial education may include:" },
      { type: "list", items: ["Creating a simple household budget", "Understanding needs versus wants", "Organizing bill due dates", "Planning for irregular income", "Building emergency savings", "Reducing unnecessary fees", "Understanding debt", "Preparing for major expenses", "Avoiding scams", "Setting small financial goals"] },
      { type: "paragraph", text: "The information should meet people where they are. A person does not need to know everything about money to take one good next step." },
      { type: "heading", text: "Support should build confidence" },
      { type: "paragraph", text: "Long-term stability is not just about numbers. It is also about confidence." },
      { type: "paragraph", text: "Financial hardship can make people feel powerless. They may believe they will always be behind or that they are incapable of managing money well." },
      { type: "paragraph", text: "Support should challenge that belief. A family may be struggling, but that does not mean they lack ability." },
      { type: "paragraph", text: "With clear information, realistic tools, and consistent encouragement, people can begin making stronger decisions." },
      { type: "paragraph", text: "Progress may look like:" },
      { type: "list", items: ["Paying one bill on time", "Saving a small amount", "Avoiding a high-fee loan", "Starting a side business", "Completing a skills program", "Reducing one debt", "Planning meals more carefully", "Asking for help before a crisis grows"] },
      { type: "paragraph", text: "Small wins build momentum." },
      { type: "heading", text: "Community partnerships strengthen the process" },
      { type: "paragraph", text: "No organization can meet every need alone." },
      { type: "paragraph", text: "Families may benefit from referrals to:" },
      { type: "list", items: ["Local food programs", "Employment organizations", "Schools", "Churches", "Health providers", "Housing resources", "Training programs", "Financial counselors", "Community leaders", "Government or nonprofit assistance"] },
      { type: "paragraph", text: "Strong partnerships help families access support beyond one program." },
      { type: "paragraph", text: "The goal should not be to keep people connected to one organization forever. The goal should be to help them build a wider circle of reliable support." },
      { type: "heading", text: "Relief and stability belong together" },
      { type: "paragraph", text: "Relief without a long-term plan may provide temporary comfort but leave the underlying problem untouched." },
      { type: "paragraph", text: "A long-term plan without immediate relief may ignore the urgency of what a family is facing today." },
      { type: "paragraph", text: "Both are necessary." },
      { type: "paragraph", text: "Relief says: \"We see your need, and we are willing to help right now.\"" },
      { type: "paragraph", text: "Stability says: \"We also believe there is a path forward.\"" },
      { type: "paragraph", text: "That is the heart of The Daily Bread Project." },
      { type: "paragraph", text: "We want to meet practical needs while helping families build stronger foundations." },
      { type: "paragraph", text: "That may begin with groceries, solar lighting, household supplies, or emergency support. But the hope is that it continues through education, planning, opportunity, and renewed confidence." },
      { type: "paragraph", text: "Because the goal is not only to help a family survive this month. The goal is to help them believe they can build a steadier future." },
    ],
  },
];
