export const resources = [
  {
    title: "Simple Family Budget Guide",
    slug: "simple-family-budget-guide",
    image: "/images/resources/family-budget-guide.svg",
    category: "Financial Education",
    description: "A starter resource for household planning and basic budgeting.",
    fileType: "PDF",
    downloadLink: "/resources/01_Simple_Family_Budget_Guide.pdf",
    gated: true,
    emailRequired: true,
    active: true,
  },
  {
    title: "Emergency Household Checklist",
    slug: "emergency-household-checklist",
    image: "/images/resources/emergency-household-checklist.svg",
    category: "Emergency Resources",
    description: "A practical checklist for preparing essential household needs.",
    fileType: "PDF",
    downloadLink: "/resources/02_Emergency_Household_Checklist.pdf",
    gated: false,
    emailRequired: false,
    active: true,
  },
  {
    title: "Widow Support Resource Guide",
    slug: "widow-support-resource-guide",
    image: "/images/resources/widow-support-resource-guide.svg",
    category: "Widow Support",
    description: "A guide for compassionate widow support, dignity-centered care, and practical referrals.",
    fileType: "PDF",
    downloadLink: "/resources/03_Widow_Support_Resource_Guide.pdf",
    gated: true,
    emailRequired: true,
    active: true,
  },
  {
    title: "Church Fundraising Toolkit",
    slug: "church-fundraising-toolkit",
    image: "/images/resources/church-fundraising-toolkit.svg",
    category: "Church Toolkits",
    description: "A toolkit for churches planning approved fundraising efforts.",
    fileType: "PDF",
    downloadLink: "/resources/04_Church_Fundraising_Toolkit.pdf",
    gated: true,
    emailRequired: true,
    active: true,
  },
  {
    title: "Volunteer Starter Guide",
    slug: "volunteer-starter-guide",
    image: "/images/resources/volunteer-starter-guide.svg",
    category: "Volunteer Materials",
    description: "A starter guide for volunteers preparing to serve with dignity, clarity, and care.",
    fileType: "PDF",
    downloadLink: "/resources/05_Volunteer_Starter_Guide.pdf",
    gated: true,
    emailRequired: true,
    active: true,
  },
  {
    title: "Community Partnership Checklist",
    slug: "community-partnership-checklist",
    image: "/images/resources/community-partnership-checklist.svg",
    category: "Partner Guides",
    description: "A planning checklist for churches, nonprofits, and community partners.",
    fileType: "PDF",
    downloadLink: "/resources/06_Community_Partnership_Checklist.pdf",
    gated: true,
    emailRequired: true,
    active: true,
  },
];

export const publishedResources = resources.filter((resource) => resource.active || resource.slug);
